version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: realworld-postgres-dev
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realworld"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: realworld-postgres-test
    environment:
      POSTGRES_DB: realworld_test
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realworld"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:
  postgres-test-data:
