services:
  postgres:
    image: postgres:18
    container_name: realworld-postgres
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realworld"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
